version: "3.7"
   
services:
  redis:
        image: redis:5.0.7
        ports:
            - "6379:6379"
  celery:
    build: .
    command: celery worker -A task_app --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
         
