# Generated by Django 2.2.6 on 2020-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.SmallIntegerField(choices=[(2, 'PENDING'), (3, 'FINISHED'), (1, 'NOT_STARTED')], default=1),
        ),
    ]
