# Generated by Django 2.2.6 on 2020-09-19 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_task', '0005_auto_20200918_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='http_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.SmallIntegerField(choices=[(3, 'FINISHED'), (2, 'PENDING'), (1, 'NOT_STARTED')], default=1),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 17, 4, 16, 935246)),
        ),
    ]
